{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "c0630d74-02de-40fa-833b-97f9bb821a51",
   "metadata": {},
   "source": [
    "## Assignment 01"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "eeee8e76-9450-4d51-9a89-e4d3723c4d95",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>label</th>\n",
       "      <th>text</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Wirtschaft</td>\n",
       "      <td>Die Gewerkschaft GPA-djp lanciert den \"All-in-...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Sport</td>\n",
       "      <td>Franzosen verteidigen 2:1-Führung – Kritische ...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Web</td>\n",
       "      <td>Neues Video von Designern macht im Netz die Ru...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Sport</td>\n",
       "      <td>23-jähriger Brasilianer muss vier Spiele pausi...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>International</td>\n",
       "      <td>Aufständische verwendeten Chemikalie bei Gefec...</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "           label                                               text\n",
       "0     Wirtschaft  Die Gewerkschaft GPA-djp lanciert den \"All-in-...\n",
       "1          Sport  Franzosen verteidigen 2:1-Führung – Kritische ...\n",
       "2            Web  Neues Video von Designern macht im Netz die Ru...\n",
       "3          Sport  23-jähriger Brasilianer muss vier Spiele pausi...\n",
       "4  International  Aufständische verwendeten Chemikalie bei Gefec..."
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import pandas as pd\n",
    "file_path: str = \"data/news_data.csv\"\n",
    "\n",
    "df = pd.read_csv(file_path, sep=';', header=None, names=['label', 'text'], quotechar=\"'\")\n",
    "df.head()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}

In [34]:
import pandas as pd
file_path: str = "data/news_data.csv"

df = pd.read_csv(file_path, sep=';', header=None, names=['label', 'text'], quotechar="'")
df.head()

# Aufgabe 1: Leere Zeilen und Dublikate entfernen

df.dropna(inplace=True)
df.drop_duplicates(inplace=True)

print(df.shape)
df.head(10)

(1028, 2)

           label                                               text
0     Wirtschaft  Die Gewerkschaft GPA-djp lanciert den "All-in-...
1          Sport  Franzosen verteidigen 2:1-Führung – Kritische ...
2            Web  Neues Video von Designern macht im Netz die Ru...
3          Sport  23-jähriger Brasilianer muss vier Spiele pausi...
4  International  Aufständische verwendeten Chemikalie bei Gefec...
5            Web  Bewährungs- und Geldstrafe für 26-Jährigen weg...
6          Sport  ÖFB-Teamspieler nur sechs Minuten nach seinem ...
7       Panorama  Ein 31-jähriger Polizist soll einer 42-Jährige...
8  International  18 Menschen verschleppt. Kabul – Nach einem Hu...
9            Web  Deutschland und Frankreich am stärksten von Lo...

In [35]:
# deutsche stopwörter laden
stop_words = set(stopwords.words('german'))

def clean_text(s):
    s = s.lower()  # nur kleinbuchstaben
    tokens = s.split()  # einfach in wörter splitten
    tokens = [w for w in tokens if w not in stop_words]  # stopwords entfernen
    return ' '.join(tokens)  # wieder zusammenbauen

df['text'] = df['text'].apply(clean_text)
df.head(10)

           label                                               text
0     Wirtschaft  gewerkschaft gpa-djp lanciert "all-in-rechner"...
1          Sport  franzosen verteidigen 2:1-führung – kritische ...
2            Web  neues video designern macht netz runde – schla...
3          Sport  23-jähriger brasilianer vier spiele pausieren ...
4  International  aufständische verwendeten chemikalie gefechten...
5            Web  bewährungs- geldstrafe 26-jährigen wegen auslä...
6          Sport  öfb-teamspieler sechs minuten tor beim 1:1 sun...
7       Panorama  31-jähriger polizist 42-jährigen knöchel gebro...
8  International  18 menschen verschleppt. kabul – hubschrauber-...
9            Web  deutschland frankreich stärksten locky betroff...

In [36]:
from sklearn.preprocessing import LabelEncoder

# LabelEncoder initialisieren
label_encoder = LabelEncoder()

# Labels encodieren (in deiner Fall-Spalte 'category' oder was immer du verwendest)
df['encoded_labels'] = label_encoder.fit_transform(df['label'])

# Zeige die ersten paar Zeilen an
df.head(1000)

,label,text,encoded_labels
0,Wirtschaft,"gewerkschaft gpa-djp lanciert ""all-in-rechner""...",7
1,Sport,franzosen verteidigen 2:1-führung – kritische ...,5
2,Web,neues video designern macht netz runde – schla...,6
3,Sport,23-jähriger brasilianer vier spiele pausieren ...,5
4,International,aufständische verwendeten chemikalie gefechten...,2
...,...,...,...
995,Inland,70 prozent schätzen diesjährige matura schwer ...,1
996,Web,gut verarbeitetes gerät aktueller atom-plattfo...,6
997,Wissenschaft,frage perspektive: hubble-daten errechneten as...,8
998,Panorama,umzug asylwerber winterfestes quartier abgesch...,4
999,Web,"neues gruselspiel greift ""p.t.""-feeling auf, t...",6

In [37]:
print(df.columns)

Index(['label', 'text', 'encoded_labels'], dtype='object')